### ISSUE TITLE
Logo being too big in the 2.0.2 Changelog

### ISSUE THREAD

**Issue by MaketendoDev** [WhoCraft/TARDIS-Refined-Wiki#1]
![image](https://github.com/user-attachments/assets/e2b55150-1627-42e9-b12d-1a903fae8ae7)

**Comment by Jeryn99** [comment]
An oddly specific issue to have, especially with the version being long outdated but just for you, I have fixed it
Give the site 10 minutes to update itself and you can be a happy chap

**Comment by MaketendoDev** [comment]
Lol I just like polished things, just couldn't let this slide (:<

**Comment by Jeryn99** [comment]
> Lol I just like polished things, just couldn't let this slide (:<

Glad I could make you a happy chap
